# SPDX-FileCopyrightText: 2024 Gerald Wiese
#
# SPDX-License-Identifier: GPL-3.0-or-later

# woodpecker syntax: https://woodpecker-ci.org/docs/usage/workflow-syntax

matrix:
  PYTHON_VERSION:
    - 3.10
  MODULE:
    - health
    - health_archives
    - health_nursing
    - health_dentistry
    - health_gyneco
    - health_history
    - health_icd11
    - health_icpm
    - health_imaging
    - health_inpatient
    - health_lab
    - health_lifestyle
    - health_ophthalmology
    - health_pediatrics
    - health_pediatrics_growth_charts
    - health_pediatrics_growth_charts_who

steps:
  - name: his-tests-sqlite
    image: python:${PYTHON_VERSION}
    environment:
      DB_CACHE: /tmp/cache
    commands:
      - pip install tryton/health*
      - python -m unittest discover -vv trytond.modules.${MODULE}
    when:
      - path: 'tryton/${MODULE}/*'
